### ISSUE TITLE
Community Plugins not Populating

### ISSUE THREAD

**Issue by MacResarchGOAT** [fcskit/obsidian-eln#2]
I have been asked by my mentor to figure out how to use this resource. I am having trouble installing it properly. When I unzip the file and create a new vault from the folder it does not activate any of the community plugins that are noted as essential. I have to go into settings and turn off restricted mode, then I see 0 plugins installed. I would like to allow the system to set itself up so the settings are correct as recommended by the instructions. I'm not sure if this is a problem with me and my naivety to obsidian or an issue with ELN. Thanks!

**Comment by fcskit** [comment]
The actual vault folder is called ELN_vault . If you open this folder as vault and not the top level folder that is create when you unzip the zip archive, everything should be working as expected.

Another way to identify the vault folder is to look for the .obsidian folder, because every obsidian vault must contain a .obsidian folder on root level.

Hope this solves your problem.



Am 24.09.2024 um 23:40 schrieb MacResarchGOAT ***@***.***>:

﻿

I have been asked by my mentor to figure out how to use this resource. I am having trouble installing it properly. When I unzip the file and create a new vault from the folder it does not activate any of the community plugins that are noted as essential. I have to go into settings and turn off restricted mode, then I see 0 plugins installed. I would like to allow the system to set itself up so the settings are correct as recommended by the instructions. I'm not sure if this is a problem with me and my naivety to obsidian or an issue with ELN. Thanks!
